set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

setw -g mode-keys vi

# j/k: pane 이동
bind j select-pane -t :.-
bind k select-pane -t :.+

# `a + g` lazygit  `a + l`/`s` yazi
bind a switch-client -T app \; display-message "app: [g]lazygit  [l]yazi"
bind -T app g display-popup -E -w 85% -h 85% -d "#{pane_current_path}" "lazygit"
bind -T app l split-window -c "#{pane_current_path}" "yazi"
bind -T app s split-window -c "#{pane_current_path}" "yazi"
