set -g extended-keys on
set -g extended-keys-format csi-u
set -g allow-passthrough on
set -g focus-events on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

setw -g mode-keys vi

# j/k: pane
bind j select-pane -t :.-
bind k select-pane -t :.+
