set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g extended-keys always
set -g extended-keys-format csi-u
set -g allow-passthrough on
set -as terminal-features 'xterm*:extkeys'

set -g focus-events on
setw -g mode-keys vi

# j/k: pane
bind j select-pane -t :.-
bind k select-pane -t :.+
